#Candy soeka wiyono - 064002200012
print ("nama kamu siapa?")
x = input()
print ("hallo selamat siang," + x)
print ("dari mana asal kamu candy?")
y = input()
print ("Wah dari," + y)
print("Sebelumnya bersekolah dimana?")
z = input()
print('Pasti menyenangkan bersekokah di,' + z)